### ISSUE TITLE
Designs.

### ISSUE THREAD

**Issue by xmyoard** [Alex0622/Alex0622.github.io#1]
Yoooo
I saw your website everything works in front of Logic, but the designs need a change.
so can I contribute to your project?
And I asked because I don't know whether it's a private project where you only like to make changes.

Best Regards,
Adarsh A

**Comment by Alex22sv** [comment]
As I mentioned before, this is a test website and it's still in development. So, if you have suggestions you can open a pull request, if I think they are okay enough I will accept the changes.

**Comment by xmyoard** [comment]
oh, okay 
I have seen some changes in the index file, I'll start working on it and I'll create a pull request as soon as possible. 
thanks.
